# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' unlock an R package on the R search() path
#' 
#' Note: R package base is unlocked by design
#' 
#' @param env environment
#' e.g as.environment(2)
#' e.g getNamespace("Rango"))
#' @export
unlockEnvironment <- function(env) {
    .Call('_Rango_unlockEnvironment', PACKAGE = 'Rango', env)
}

